### ISSUE TITLE
Environment variables reset if calling docker via sudo

### ISSUE THREAD

**Issue by dmontagu** [tiangolo/dockerswarm.rocks#12]
@tiangolo the main landing page has the following note about how to call docker commands using sudo:

> **Note**: If you are not a root user, you might need to add sudo to these commands. The shell will tell you when you don't have enough permissions.

What it doesn't say is that when you make calls via sudo, the environment is reset (well, at least in ubuntu), so the environment variable substitutions in `traefik.yml` actually are replaced with blanks. Unfortunately, this doesn't cause obvious errors in the docker stack launch, so it was hard for me to get to the bottom of what was wrong.

This can be fixed by just adding the `-E` flag to the sudo command to pass the environment variables:
```
sudo -E docker stack deploy -c traefik-host.yml traefik-consul
```
worked for me.

I think it would be a good idea to add this to the warning there (it would have saved me a couple hours of frustration). I'll make a pull request with some suggested phrasing but feel free to ignore or place the warning elsewhere as you see fit.

**Comment by dmrty** [comment]
FYI, I've started to use `${VARIABLE:?Variable not found}` when there is no obvious default so that the deploy crash if the variable is not set: 
See docker reference on [variable substitution](https://docs.docker.com/compose/compose-file/#variable-substitution) for more info. 
Maybe that would make sense to change the `${VARIABLE}` or `${VARIABLE:-}` by `${VARIABLE:?}` for a more solid deploy process?

**Comment by tiangolo** [comment]
Good idea @dmrty ! I'll change it later (unless a PR doing it comes first :grin: ).

**Comment by dmrty** [comment]
I'll try to work on a PR. Let me open another issue specificially for this ${VARIABLE:?} question  (instead of poluting this issue) and i'll work at a PR for it. 👌

**Comment by tiangolo** [comment]
Thanks @dmrty ! Let's move to the new issue for that.

@dmontagu as your PR fixing the `sudo` part it is merged already, I'll close this issue now.

**Comment by anatoly-khomenko** [comment]
When running:
`sudo docker stack deploy -c traefik.yml traefik-consul`
I was getting:
`invalid interpolation format for services.consul-leader.deploy.labels.[]: "required variable DOMAIN is missing a value: Variable DOMAIN not set". You may need to escape any $ with another $.`

unless I specified -E flag as @dmontagu proposed:
`sudo -E docker stack deploy -c traefik.yml traefik-consul`

It would be good to reflect this in the instruction, as the error text made me try to fix yml syntax instead of looking elsewhere.
